nome_curso = '   Edição de Vídeo   '
print(nome_curso.upper())
print('==================')
print(nome_curso.lower())
print('==================')
print(nome_curso.strip())
print('==================')
print(nome_curso.lstrip())
print('==================')
print(nome_curso.rstrip())
print('==================')
print(nome_curso.find('ção'))
print('==================')
print(nome_curso.replace('Vídeo','Música')) 
print('==================')
print('https://sc.olx.com.br/?o=90&q=relogio'.replace('relogio', 'carro'))
print('==================')
